[build]
  publish = "dist"
  command = "npm run generate:netlify"

[build.environment]
  NODE_VERSION = "16"

# Redirecciones y cabeceras si son necesarias
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

#[[headers]]
#  for = "/*"
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"
